package org.contourdynamics.cms.models;

import javax.inject.Inject;
import javax.enterprise.inject.Model;
import org.contourdynamics.cms.Entities.BpCmpy;
/**
 * BpCmpy generated by hbm2java
 */
@Model
public class BpCmpyModel {
//	@Inject
//	 UserIdentityRepos Repos;
	 
//	 public String SaveUser(UserIdentity user)
//	 {
//		 Repos.save(user);
//		 return "";
//	 }


}
