package org.contourdynamics.cms.models;

import javax.inject.Inject;
import javax.enterprise.inject.Model;
import org.contourdynamics.cms.Entities.BpContactAccount;
// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * BpContactAccount generated by hbm2java
 */
@Model
public class BpContactAccountModel  {
//	@Inject
//	 UserIdentityRepos Repos;
	 
//	 public String SaveUser(UserIdentity user)
//	 {
//		 Repos.save(user);
//		 return "";
//	 }

}
