package org.contourdynamics.cms.models;

import javax.inject.Inject;
import javax.enterprise.inject.Model;
import org.contourdynamics.cms.Entities.BpMain;
// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1



/**
 * BpMain generated by hbm2java
 */
@Model
public class BpMainModel {



}
