package org.contourdynamics.cms.models;

import java.util.List;

import javax.inject.Inject;
import javax.enterprise.inject.Model;
import org.contourdynamics.cms.Entities.BpMain;
import org.contourdynamics.cms.repository.BpMainRepos;
// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * BpMain generated by hbm2java
 */
@Model
public class BpMainModel {

	@Inject
	BpMainRepos Repos;
	
	public String Save(BpMain user)
	{
		Repos.save(user);
		return "";
	}
	public List<BpMain> ReadAll()
	{
		return Repos.findAll();
	}
	public List<BpMain> ReadAllCustomers()
	{
		List<BpMain> result = Repos.findAllCustomer(2);
		return result;
	}
	 
}
