package org.contourdynamics.cms.models;

import java.util.List;

import javax.inject.Inject;
import javax.enterprise.inject.Model;

import org.contourdynamics.cms.Entities.StatusCode;
import org.contourdynamics.cms.repository.StatusCodeRepos;
/**
 * StatusCode generated by hbm2java
 */
@Model
public class StatusCodeModel {

	@Inject
	StatusCodeRepos Repos;
	
	public String Save(StatusCode Status)
	{
		Repos.save(Status);
		return "Saved";
	}
	public List<StatusCode> ReadAll()
	{
		return Repos.findAll();
	}

}
