package org.contourdynamics.cms.models;

import javax.inject.Inject;
import javax.enterprise.inject.Model;
import org.contourdynamics.cms.Entities.TitleCode;
/**
 * TitleCode generated by hbm2java
 */
@Model
public class TitleCodeModel {


}
