package org.contourdynamics.cms.Entities;

// Generated Dec 2, 2015 6:46:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BpCmpy generated by hbm2java
 */
@Entity
@Table(name = "BP_CMPY", catalog = "smartcommunication")
public class BpCmpy implements java.io.Serializable {

	private Integer id;
	private BpMain bpMain;
	private String companyname;
	private String website;
	private Date establishedsince;

	public BpCmpy() {
	}

	public BpCmpy(BpMain bpMain, String companyname, String website,
			Date establishedsince) {
		this.bpMain = bpMain;
		this.companyname = companyname;
		this.website = website;
		this.establishedsince = establishedsince;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	@Column(name = "companyname", length = 45)
	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	@Column(name = "website", length = 45)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "establishedsince", length = 10)
	public Date getEstablishedsince() {
		return this.establishedsince;
	}

	public void setEstablishedsince(Date establishedsince) {
		this.establishedsince = establishedsince;
	}

}
