package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BpCmpy generated by hbm2java
 */
public class BpCmpy implements java.io.Serializable {

	private Integer id;
	private BpMain bpMain;
	private String companyname;
	private String website;
	private Date establishedsince;

	public BpCmpy() {
	}

	public BpCmpy(BpMain bpMain, String companyname, String website,
			Date establishedsince) {
		this.bpMain = bpMain;
		this.companyname = companyname;
		this.website = website;
		this.establishedsince = establishedsince;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getEstablishedsince() {
		return this.establishedsince;
	}

	public void setEstablishedsince(Date establishedsince) {
		this.establishedsince = establishedsince;
	}

}
