package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 11:11:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpContactAccount generated by hbm2java
 */
@Entity
@Table(name = "BP_ContactAccount", catalog = "smartcommunication")
public class BpContactAccount implements java.io.Serializable {

	private Integer id;
	private StatusCode statusCode;
	private ContactAccountCode contactAccountCode;
	private String description;
	private String accountId;
	private String extensions;

	public BpContactAccount() {
	}

	public BpContactAccount(StatusCode statusCode,
			ContactAccountCode contactAccountCode, String description,
			String accountId, String extensions) {
		this.statusCode = statusCode;
		this.contactAccountCode = contactAccountCode;
		this.description = description;
		this.accountId = accountId;
		this.extensions = extensions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountType")
	public ContactAccountCode getContactAccountCode() {
		return this.contactAccountCode;
	}

	public void setContactAccountCode(ContactAccountCode contactAccountCode) {
		this.contactAccountCode = contactAccountCode;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "AccountID")
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "Extensions", length = 45)
	public String getExtensions() {
		return this.extensions;
	}

	public void setExtensions(String extensions) {
		this.extensions = extensions;
	}

}
