package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * BpContactAccount generated by hbm2java
 */
public class BpContactAccount implements java.io.Serializable {

	private Integer id;
	private StatusCode statusCode;
	private ContactAccountCode contactAccountCode;
	private String description;
	private String accountId;
	private String extensions;

	public BpContactAccount() {
	}

	public BpContactAccount(StatusCode statusCode,
			ContactAccountCode contactAccountCode, String description,
			String accountId, String extensions) {
		this.statusCode = statusCode;
		this.contactAccountCode = contactAccountCode;
		this.description = description;
		this.accountId = accountId;
		this.extensions = extensions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	public ContactAccountCode getContactAccountCode() {
		return this.contactAccountCode;
	}

	public void setContactAccountCode(ContactAccountCode contactAccountCode) {
		this.contactAccountCode = contactAccountCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getExtensions() {
		return this.extensions;
	}

	public void setExtensions(String extensions) {
		this.extensions = extensions;
	}

}
