package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BpIndv generated by hbm2java
 */
public class BpIndv implements java.io.Serializable {

	private Integer id;
	private BpMain bpMain;
	private GenderCode genderCode;
	private TitleCode titleCode;
	private String firstname;
	private String middlename;
	private String lastname;
	private Date dateofbirth;
	private Integer ageyears;
	private Integer months;

	public BpIndv() {
	}

	public BpIndv(BpMain bpMain, GenderCode genderCode, TitleCode titleCode,
			String firstname, String middlename, String lastname,
			Date dateofbirth, Integer ageyears, Integer months) {
		this.bpMain = bpMain;
		this.genderCode = genderCode;
		this.titleCode = titleCode;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.dateofbirth = dateofbirth;
		this.ageyears = ageyears;
		this.months = months;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	public GenderCode getGenderCode() {
		return this.genderCode;
	}

	public void setGenderCode(GenderCode genderCode) {
		this.genderCode = genderCode;
	}

	public TitleCode getTitleCode() {
		return this.titleCode;
	}

	public void setTitleCode(TitleCode titleCode) {
		this.titleCode = titleCode;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	public Integer getAgeyears() {
		return this.ageyears;
	}

	public void setAgeyears(Integer ageyears) {
		this.ageyears = ageyears;
	}

	public Integer getMonths() {
		return this.months;
	}

	public void setMonths(Integer months) {
		this.months = months;
	}

}
