package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 11:11:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BpMain generated by hbm2java
 */
@Entity
@Table(name = "BP_Main", catalog = "smartcommunication")
public class BpMain implements java.io.Serializable {

	private Integer id;
	private StatusCode statusCode;
	private String description;
	private Integer type;
	private Set<BpSysUser> bpSysUsers = new HashSet<BpSysUser>(0);
	private Set<BpIndv> bpIndvs = new HashSet<BpIndv>(0);
	private Set<BpRoles> bpRoleses = new HashSet<BpRoles>(0);
	private Set<BpCmpy> bpCmpies = new HashSet<BpCmpy>(0);

	public BpMain() {
	}

	public BpMain(StatusCode statusCode, String description, Integer type,
			Set<BpSysUser> bpSysUsers, Set<BpIndv> bpIndvs,
			Set<BpRoles> bpRoleses, Set<BpCmpy> bpCmpies) {
		this.statusCode = statusCode;
		this.description = description;
		this.type = type;
		this.bpSysUsers = bpSysUsers;
		this.bpIndvs = bpIndvs;
		this.bpRoleses = bpRoleses;
		this.bpCmpies = bpCmpies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpMain")
	public Set<BpSysUser> getBpSysUsers() {
		return this.bpSysUsers;
	}

	public void setBpSysUsers(Set<BpSysUser> bpSysUsers) {
		this.bpSysUsers = bpSysUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpMain")
	public Set<BpIndv> getBpIndvs() {
		return this.bpIndvs;
	}

	public void setBpIndvs(Set<BpIndv> bpIndvs) {
		this.bpIndvs = bpIndvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpMain")
	public Set<BpRoles> getBpRoleses() {
		return this.bpRoleses;
	}

	public void setBpRoleses(Set<BpRoles> bpRoleses) {
		this.bpRoleses = bpRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpMain")
	public Set<BpCmpy> getBpCmpies() {
		return this.bpCmpies;
	}

	public void setBpCmpies(Set<BpCmpy> bpCmpies) {
		this.bpCmpies = bpCmpies;
	}

}
