package org.contourdynamics.cms.Entities;

// Generated Dec 2, 2015 6:46:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpRoles generated by hbm2java
 */
@Entity
@Table(name = "BP_Roles", catalog = "smartcommunication")
public class BpRoles implements java.io.Serializable {

	private Integer id;
	private RoleCode roleCode;
	private BpMain bpMain;
	private StatusCode statusCode;

	public BpRoles() {
	}

	public BpRoles(RoleCode roleCode, BpMain bpMain, StatusCode statusCode) {
		this.roleCode = roleCode;
		this.bpMain = bpMain;
		this.statusCode = statusCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role")
	public RoleCode getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(RoleCode roleCode) {
		this.roleCode = roleCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StatusCode")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

}
