package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * BpRoles generated by hbm2java
 */
public class BpRoles implements java.io.Serializable {

	private Integer id;
	private StatusCode statusCode;
	private BpMain bpMain;
	private String role;

	public BpRoles() {
	}

	public BpRoles(StatusCode statusCode, BpMain bpMain, String role) {
		this.statusCode = statusCode;
		this.bpMain = bpMain;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
