package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 11:11:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpRoles generated by hbm2java
 */
@Entity
@Table(name = "BP_Roles", catalog = "smartcommunication")
public class BpRoles implements java.io.Serializable {

	private Integer id;
	private StatusCode statusCode;
	private BpMain bpMain;
	private String role;

	public BpRoles() {
	}

	public BpRoles(StatusCode statusCode, BpMain bpMain, String role) {
		this.statusCode = statusCode;
		this.bpMain = bpMain;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	@Column(name = "Role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
