package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * BpSysUser generated by hbm2java
 */
public class BpSysUser implements java.io.Serializable {

	private Integer id;
	private BpMain bpMain;
	private Integer realm;
	private String user;

	public BpSysUser() {
	}

	public BpSysUser(BpMain bpMain, Integer realm, String user) {
		this.bpMain = bpMain;
		this.realm = realm;
		this.user = user;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	public Integer getRealm() {
		return this.realm;
	}

	public void setRealm(Integer realm) {
		this.realm = realm;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
