package org.contourdynamics.cms.Entities;

// Generated Dec 2, 2015 6:46:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BpSysUser generated by hbm2java
 */
@Entity
@Table(name = "BP_SYS_USER", catalog = "smartcommunication")
public class BpSysUser implements java.io.Serializable {

	private Integer id;
	private Realm realm;
	private StatusCode statusCode;
	private String user;
	private Set<BpMain> bpMains = new HashSet<BpMain>(0);

	public BpSysUser() {
	}

	public BpSysUser(Realm realm, StatusCode statusCode, String user,
			Set<BpMain> bpMains) {
		this.realm = realm;
		this.statusCode = statusCode;
		this.user = user;
		this.bpMains = bpMains;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Realm")
	public Realm getRealm() {
		return this.realm;
	}

	public void setRealm(Realm realm) {
		this.realm = realm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StatusCode")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "user")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpSysUser")
	public Set<BpMain> getBpMains() {
		return this.bpMains;
	}

	public void setBpMains(Set<BpMain> bpMains) {
		this.bpMains = bpMains;
	}

}
