package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 11:11:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpSysUser generated by hbm2java
 */
@Entity
@Table(name = "BP_SYS_USER", catalog = "smartcommunication")
public class BpSysUser implements java.io.Serializable {

	private Integer id;
	private BpMain bpMain;
	private Integer realm;
	private String user;

	public BpSysUser() {
	}

	public BpSysUser(BpMain bpMain, Integer realm, String user) {
		this.bpMain = bpMain;
		this.realm = realm;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	@Column(name = "Realm")
	public Integer getRealm() {
		return this.realm;
	}

	public void setRealm(Integer realm) {
		this.realm = realm;
	}

	@Column(name = "user")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
