package org.contourdynamics.cms.Entities;

// Generated Dec 2, 2015 6:46:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BpTypeCode generated by hbm2java
 */
@Entity
@Table(name = "BP_TYPE_CODE", catalog = "smartcommunication")
public class BpTypeCode implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set<BpMain> bpMains = new HashSet<BpMain>(0);

	public BpTypeCode() {
	}

	public BpTypeCode(String description, Set<BpMain> bpMains) {
		this.description = description;
		this.bpMains = bpMains;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpTypeCode")
	public Set<BpMain> getBpMains() {
		return this.bpMains;
	}

	public void setBpMains(Set<BpMain> bpMains) {
		this.bpMains = bpMains;
	}

}
