package org.contourdynamics.cms.Entities;

// Generated Dec 2, 2015 6:46:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactAccountCode generated by hbm2java
 */
@Entity
@Table(name = "ContactAccountCode", catalog = "smartcommunication")
public class ContactAccountCode implements java.io.Serializable {

	private Integer id;
	private String contactAccountCodecol;
	private Set<BpContactAccount> bpContactAccounts = new HashSet<BpContactAccount>(
			0);

	public ContactAccountCode() {
	}

	public ContactAccountCode(String contactAccountCodecol,
			Set<BpContactAccount> bpContactAccounts) {
		this.contactAccountCodecol = contactAccountCodecol;
		this.bpContactAccounts = bpContactAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ContactAccountCodecol", length = 45)
	public String getContactAccountCodecol() {
		return this.contactAccountCodecol;
	}

	public void setContactAccountCodecol(String contactAccountCodecol) {
		this.contactAccountCodecol = contactAccountCodecol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAccountCode")
	public Set<BpContactAccount> getBpContactAccounts() {
		return this.bpContactAccounts;
	}

	public void setBpContactAccounts(Set<BpContactAccount> bpContactAccounts) {
		this.bpContactAccounts = bpContactAccounts;
	}

}
