package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ContactAccountCode generated by hbm2java
 */
public class ContactAccountCode implements java.io.Serializable {

	private Integer id;
	private String contactAccountCodecol;
	private Set<BpContactAccount> bpContactAccounts = new HashSet<BpContactAccount>(
			0);

	public ContactAccountCode() {
	}

	public ContactAccountCode(String contactAccountCodecol,
			Set<BpContactAccount> bpContactAccounts) {
		this.contactAccountCodecol = contactAccountCodecol;
		this.bpContactAccounts = bpContactAccounts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContactAccountCodecol() {
		return this.contactAccountCodecol;
	}

	public void setContactAccountCodecol(String contactAccountCodecol) {
		this.contactAccountCodecol = contactAccountCodecol;
	}

	public Set<BpContactAccount> getBpContactAccounts() {
		return this.bpContactAccounts;
	}

	public void setBpContactAccounts(Set<BpContactAccount> bpContactAccounts) {
		this.bpContactAccounts = bpContactAccounts;
	}

}
