package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GenderCode generated by hbm2java
 */
public class GenderCode implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set<BpIndv> bpIndvs = new HashSet<BpIndv>(0);

	public GenderCode() {
	}

	public GenderCode(String description, Set<BpIndv> bpIndvs) {
		this.description = description;
		this.bpIndvs = bpIndvs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<BpIndv> getBpIndvs() {
		return this.bpIndvs;
	}

	public void setBpIndvs(Set<BpIndv> bpIndvs) {
		this.bpIndvs = bpIndvs;
	}

}
