package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 11:11:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Realm generated by hbm2java
 */
@Entity
@Table(name = "Realm", catalog = "smartcommunication")
public class Realm implements java.io.Serializable {

	private Integer id;
	private String description;
	private Integer statusCode;
	private String domain;

	public Realm() {
	}

	public Realm(String description, Integer statusCode, String domain) {
		this.description = description;
		this.statusCode = statusCode;
		this.domain = domain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status_code")
	public Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "domain", length = 45)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

}
