package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * Realm generated by hbm2java
 */
public class Realm implements java.io.Serializable {

	private Integer id;
	private String description;
	private Integer statusCode;
	private String domain;

	public Realm() {
	}

	public Realm(String description, Integer statusCode, String domain) {
		this.description = description;
		this.statusCode = statusCode;
		this.domain = domain;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

}
