package org.contourdynamics.cms.Entities;

// Generated Nov 28, 2015 8:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StatusCode generated by hbm2java
 */
public class StatusCode implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set<BpRoles> bpRoleses = new HashSet<BpRoles>(0);
	private Set<BpContactAccount> bpContactAccounts = new HashSet<BpContactAccount>(
			0);
	private Set<BpMain> bpMains = new HashSet<BpMain>(0);

	public StatusCode() {
	}

	public StatusCode(String description, Set<BpRoles> bpRoleses,
			Set<BpContactAccount> bpContactAccounts, Set<BpMain> bpMains) {
		this.description = description;
		this.bpRoleses = bpRoleses;
		this.bpContactAccounts = bpContactAccounts;
		this.bpMains = bpMains;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<BpRoles> getBpRoleses() {
		return this.bpRoleses;
	}

	public void setBpRoleses(Set<BpRoles> bpRoleses) {
		this.bpRoleses = bpRoleses;
	}

	public Set<BpContactAccount> getBpContactAccounts() {
		return this.bpContactAccounts;
	}

	public void setBpContactAccounts(Set<BpContactAccount> bpContactAccounts) {
		this.bpContactAccounts = bpContactAccounts;
	}

	public Set<BpMain> getBpMains() {
		return this.bpMains;
	}

	public void setBpMains(Set<BpMain> bpMains) {
		this.bpMains = bpMains;
	}

}
